# Generated by Django 2.0.7 on 2018-08-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, unique=True)),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('password', models.CharField(max_length=70, unique=True)),
            ],
        ),
    ]
