# Generated by Django 2.0.7 on 2018-08-11 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
