# Generated by Django 2.0.7 on 2018-08-14 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.TextField(max_length=100)),
                ('post_type', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('date', models.DateField(auto_now=True)),
                ('num_of_people', models.IntegerField()),
                ('theme', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Profile')),
            ],
        ),
    ]
