# Generated by Django 2.0.7 on 2018-08-17 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_auto_20180816_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='num_of_people',
            field=models.IntegerField(),
        ),
    ]
